### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by jkr1987** [unode/firefox_decrypt#103]
Hello ,
i'm tring to use firefox_decrypt.py but test don't work.

i work on linux 64bit

$python firefox_decrypt.py tests/test_data/
Select the Mozilla profile you wish to decrypt
1 -> test_profile_firefox_20
2 -> test_profile_firefox_46
3 -> test_profile_firefox_nopassword_46
4 -> test_profile_firefox_59
5 -> test_profile_firefox_LЮшр
6 -> test_profile_firefox_nopassword_59
1
2024-02-28 23:03:16,990 - ERROR - Couldn't initialize NSS, maybe 'tests/test_data/test_profile_firefox_20' is not a valid profile?

**Comment by unode** [comment]
Hi @jkr1987 it seems like there is some issue with your `libnss3`.
Did you install this library on your system?

If you did, could you also run the command with `python firefox_decrypt.py -vvv tests/test_data/ ` and paste the output?

**Comment by unode** [comment]
Closing as abandoned. Please reopen if it's still relevant.
