### ISSUE TITLE
Add support for snap version of firefox

### ISSUE THREAD

**Issue by its-Winter** [unode/firefox_decrypt#111]
**Is your feature request related to a problem? Please describe.**
No open problems about this only an idea. 

**Describe the solution you'd like**
Add the snap install path of firefox as an switch option or do a check path to see if there's either for the default path. I had to pass the path my self `~/snap/firefox/common/.mozilla/firefox` - for system installed Ubuntu firefox.

**Describe alternatives you've considered**
Pass it manually, but this would be an easy enhancement.

**Additional context**
thang works like a charm otherwise.

**Comment by unode** [comment]
Closed as won't fix given `profile_path` can be specified as an argument.
