### ISSUE TITLE
Asking for Master Password when there is none FF 52.0

### ISSUE THREAD

**Issue by dshimer** [Unode/firefox_decrypt#12]
I am running Firefox 52.0 64bit on Ubuntu 16.10 and have used this with no issues in the past but not for a couple of months.  Now when I run it I am prompted

> Master Password for profile NameOfDefaultProfile:

But I have no master password set.

The first couple times I did it with a blank I got a segfault.  I tried my system password and my mozilla password and just got a message that it was incorrect.  Then for some reason it started working with a blank and now it does that with a message about attempting without a default password and works fine.

**Comment by Unode** [comment]
Hi Dennis,

Asking for a master password has always been the default behavior, even if you don't have one.
The segfault could have been due to the same problem that was fixed in #9.

From what I understand there isn't really a problem right?
