### ISSUE TITLE
libnss3 usage is a bit crude and has memory leaks

### ISSUE THREAD

**Issue by ser2-creator** [Unode/firefox_decrypt#13]
First, thanks for the nice work! I always needed that tool but I never trusted any code. But your code is nicely understandable...so while checking the code I noticed a few bugs related to the libnss3 usage.

1) In get_keyslot there is a strange cast required to avoid segfaults (my system is affected). I think, the reason is that the return value is not void_p but a pointer to a struct.
2) There is a memory leak, because the SECItems are not freed.
3) The keyslot is also not freed, which causes the NSS_Shutdown to fail always.

There seems to be no real documentation of libnss3, but attached is a class which does a more accurate handling of libnss3, feel free to use it.

[nssdecoder.zip](https://github.com/Unode/firefox_decrypt/files/870723/nssdecoder.zip)

**Comment by criztovyl** [comment]
Looks nice :+1:

**Comment by Unode** [comment]
Hi @ser2-creator thanks for the code.
Indeed the implementation is crude. Mostly on 'sorta works' basis. The weird cast was a *shrug* fix for a segfault.
Your code is much nicer so I'll look into merging this soon.

**Comment by Unode** [comment]
Any name I could [credit](https://github.com/Unode/firefox_decrypt/blob/master/AUTHORS) you under?

**Comment by ser2-creator** [comment]
I prefer not to be credited :)

**Comment by Unode** [comment]
Also an option :)

**Comment by ser2-creator** [comment]
For the error messages, I use the following
```
self._makefu(ct.c_int, "PORT_GetError")
self._makefu(ct.c_char_p, "PR_ErrorToName", ct.c_int)
self._makefu(ct.c_char_p, "PR_ErrorToString", ct.c_int, ct.c_uint32)
```

and

```
try:
	code = self._PORT_GetError()
	name = self._PR_ErrorToName(code)
	name = "NULL" if name is None else name.decode("ascii")
	text = self._PR_ErrorToString(code, 0) # 0 is the default language
	text = text.decode("utf8")
except Exception: # I guess only UnicodeDecodeError could occur
	name = "?"
	text = "error getting error message"
```

I am out...

**Comment by Unode** [comment]
Merged, thanks again.
