### ISSUE TITLE
Not finding nss3 lib on mac os X

### ISSUE THREAD

**Issue by jneves** [Unode/firefox_decrypt#14]
I was getting an error like this while trying to use nss3 from both Firefox and Thunderbird.

```017-03-25 21:48:28,524 - ERROR - Problems opening 'libnss3.dylib' required for password decryption
2017-03-25 21:48:28,524 - ERROR - Error was dlopen(libnss3.dylib, 6): Library not loaded: @executable_path/libmozglue.dylib
  Referenced from: /Users/joao/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/libnss3.dylib
  Reason: unsafe use of @executable_path in libnss3.dylib with restricted binary
```

From https://bugzilla.mozilla.org/show_bug.cgi?id=578751 this is an issue that isn't going to be solved.

My final solution was to install nss from homebrew with `brew install nss` and adding `"/usr/local/opt/nss/lib",` to the paths of nss library in Darwin (around line 245).

Just opening this to inform others.

**Comment by Unode** [comment]
Thanks @jneves 
I'll make sure to document this and guide users accordingly.

**Comment by Gounlaf** [comment]
Hi @Unode,

I made this pr: #15
