### ISSUE TITLE
¿Does it work with Quantum?

### ISSUE THREAD

**Issue by mautematico** [unode/firefox_decrypt#20]
I have used it in the past with success.

Now, I am using Quantum Nightly, and I get this error message on run:

`
2018-01-05 17:12:08,531 - ERROR - Couldn't initialize NSS, maybe '/home/mautematico/.mozilla/firefox/mauricio' is not a valid profile?
`

`libnss3` is already installed on my Debian box

**Comment by unode** [comment]
Can you include the exact nighly version you are using? Thanks!

I can think of two reasons for this error:
1. The profile is new and doesn't yet have any credentials stored. (logins.json doesn't exist)
2. The latest nighlies now use a new/different storage for credentials.

For 1. you can tell Firefox to remember a few more logins and optionally set a Master Password. If it's 2. I need to read up on what has changed and implement it.

**Comment by unode** [comment]
Finally had a chance to try Firefox v59. I can confirm that indeed it doesn't work.
While the format of passwords hasn't changed, the database containing secrets did.

Oddly even the latest version of `libnss3` reports `SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.` so this might be a mistake in libnss.

This will require further investigation...

**Comment by unode** [comment]
[Asked upstream](https://groups.google.com/forum/#!topic/mozilla.dev.security/xmW-3i69rRE) about support for this functionality or loss thereof.
