### ISSUE TITLE
Thank-you

### ISSUE THREAD

**Issue by skx** [unode/firefox_decrypt#24]
This is not a bug-report, this is a simple note to say thank-you for writing this utility and for making it available.

Having moved to a new computer using this tool allowed me to easily export the few passwords which I'd not previously migrated to the [pass](https://www.passwordstore.org/) application.

Very handy, very useful, and worked without a problem for me.

**Comment by unode** [comment]
Hi Steve, thanks for the nice feedback. Very happy to hear it was useful and ran without issues.

**Comment by Krypton-Nova** [comment]
This saved an old but important mail account of mine. Password managers make it so easy you'd almost forget the password attached to an account...

So a big thank you for making this!
