### ISSUE TITLE
error...

### ISSUE THREAD

**Issue by olejaZverev** [unode/firefox_decrypt#28]
Win 7, 32x
Python 2.7
Firefox 60.0.1

C:\Users\Алиса>python C:\Users\Алиса\Desktop\firefox_decrypt.py -vvv

2018-05-17 21:34:34,355 - INFO - Running firefox_decrypt version: 0.7.0
2018-05-17 21:34:34,355 - DEBUG - Parsed commandline arguments: Namespace(choice
=None, delimiter=';', export_pass=False, format='human', interactive=True, list=
False, pass_cmd=u'pass', pass_compat='default', pass_prefix=u'web', profile='C:\
\Users\\\xc0\xeb\xe8\xf1\xe0\\AppData\\Roaming\\Mozilla\\Firefox', quotechar='"'
, tabular=False, verbose=3)
2018-05-17 21:34:34,355 - DEBUG - Skipping password store test, not exporting
2018-05-17 21:34:34,355 - DEBUG - PATH is now C:\Python27\;C:\Python27\Scripts;C
:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windo
wsPowerShell\v1.0\;C:\Program Files\Universal Extractor;C:\Program Files\Univers
al Extractor\bin;C:\Program Files\dotnet\;C:\Program Files\Mozilla Firefox
2018-05-17 21:34:34,355 - DEBUG - Loading NSS library from C:\Program Files\Mozi
lla Firefox\nss3.dll
2018-05-17 21:34:34,355 - DEBUG - Reading profiles from C:\Users\Lышёр\AppData\R
oaming\Mozilla\Firefox\profiles.ini
2018-05-17 21:34:34,371 - DEBUG - Read profiles ['General', 'Profile0']
2018-05-17 21:34:34,371 - DEBUG - Profile selection matched Profiles/7xofdivo.de
fault
2018-05-17 21:34:34,371 - DEBUG - Initializing NSS with profile path 'C:\Users\L
ышёр\AppData\Roaming\Mozilla\Firefox\Profiles/7xofdivo.default'
2018-05-17 21:34:34,371 - DEBUG - Initializing NSS returned -1
2018-05-17 21:34:34,371 - ERROR - Couldn't initialize NSS, maybe 'C:\Users\Lышёр
\AppData\Roaming\Mozilla\Firefox\Profiles/7xofdivo.default' is not a valid profi
le?
2018-05-17 21:34:34,387 - DEBUG - Error during a call to NSS library, trying to
obtain error info
2018-05-17 21:34:34,387 - DEBUG - SEC_ERROR_BAD_DATABASE: security library: bad
database.

**Comment by olejaZverev** [comment]
the username is a Russian letter. I think the error lies in this

**Comment by olejaZverev** [comment]
I'm a C ++ programmer myself and I can not fix the problem in the python.

I could check your builds until we solve the encoding problem together. if you are interested in this.

**Comment by unode** [comment]
I didn't have time too look further into this.

Reproducing this problem requires both a non-ASCII character/encoding as well as Windows neither of which I have readily at hand.

There are ongoing efforts to make tests run on [AppVeyor](https://ci.appveyor.com/project/Unode/firefox-decrypt) in the [appveyor branch](https://github.com/unode/firefox_decrypt/tree/appveyor) but this is very much work in progress.

On the other hand, since it's unclear how easy it will be to run the current Bash based tests on AppVeyor, there's also some efforts both on #25 and the [pytests branch](https://github.com/unode/firefox_decrypt/tree/pytests) to make testing more robust and convert the current testing framework to Python. 

All of this will take time and any help is most appreciated. Feel free to fork and submit pull requests.

**Comment by unode** [comment]
As for the actual NSS interaction problem, it seems Windows does not use UTF-8 as default character encoding for library interaction. From different sources I found references to different ANSI codepages and UTF-16. This will require further testing.

If you can, try changing the encoding used by the bytestring that gets passed to [NSS_Init](https://github.com/unode/firefox_decrypt/blob/f9e318fd8da0cdbd01d1d3104c8c9c5909626512/firefox_decrypt.py#L363) and see if you get it to work on your system.

**Comment by olejaZverev** [comment]
I try you last build with Python 3.6.5(on this PC too), its all right and great well.
But...need 2.7 Python for nuitka and cython.

**Comment by unode** [comment]
I've managed to reproduce the problem.
I'll hopefully have a fix in a few hours.

**Comment by unode** [comment]
Not as easy as I though, and in fact with Python 2.7 I couldn't find a compatible solution. With Python 3 it worked fine.
The problem has to do with the encoding used by `cmd.exe`.
The only alternative is to [set your terminal to be UTF8 compatible](https://stackoverflow.com/a/388500) but this has it's own problems.

So on this note and given 2.7 end of life is approaching, I'm currently dropping support for Python 2.7 on Windows.

Please try Python 3 instead and let me know how it worked.

**Comment by olejaZverev** [comment]
>>Not as easy as I though, and in fact with Python 2.7 I couldn't find a compatible solution. With Python 3 it worked fine.
The problem has to do with the encoding used by cmd.exe.
The only alternative is to set your terminal to be UTF8 compatible but this has it's own problems.

for russian language: chcp 866
but....error too.

python 3 may be one way.

**Comment by olejaZverev** [comment]
with python 3

Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\Алиса>C:\Users\Алиса\Desktop\firefox_decrypt.py
Traceback (most recent call last):
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 952, in <module>
    main()
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 918, in main
    nss = NSSInteraction()
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 413, in __init__
    self.NSS = NSSDecoder()
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 256, in __init__
    self.load_libnss()
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 370, in load_libnss
    self.NSS = self.find_nss(locations, nssname)
  File "C:\Users\Алиса\Desktop\firefox_decrypt.py", line 302, in find_nss
    os.chdir(loc)
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:\\Pr
ogram Files (x86)\\Mozilla Firefox'

My system not have this path. Right path is: C:\Program Files\Mozilla Firefox

**Comment by unode** [comment]
Sorry that was a mistake on my part. Can you try the latest commit?

**Comment by olejaZverev** [comment]
I try last commit. Work correctly.
