### ISSUE TITLE
Multiline format for pass? 

### ISSUE THREAD

**Issue by hyiltiz** [unode/firefox_decrypt#35]
Is there any way to generate a single file in the pass multiline format instead? Simply not using `--pass-compat` flag didn't seem to help, as it still produced a directory structure. I think this is very close to the default behavior, or may simply be achieved by redirecting from the stdout.

**Comment by unode** [comment]
I'm not sure I follow... Do you want to export all your (firefox) profile passwords into a single `pass` entry?

If so, no this isn't supported/implemented.

It can however be easily achieved by exporting to `csv` or similar format and then importing to `pass` externally.

**Comment by unode** [comment]
Has the `csv` workaround solved your issue?

**Comment by hyiltiz** [comment]
What I asked was, as you pointed out, not supported by `pass`. Guess time to close this one.
