### ISSUE TITLE
Encoding issue on Windows

### ISSUE THREAD

**Issue by lgommans** [unode/firefox_decrypt#39]
When running the program without arguments or with the `-f csv` argument, it successfully runs. When then adding an output redirect, e.g. `... >..\example.csv`, it shows the following error:

    PS D:\progfiles\firefox> python C:\users\x\firefox-decrypt.py -f csv > ..\example.csv

    Master Password for profile C:\Users\x\AppData\Roaming\Mozilla\Firefox\Profiles/x.default:
Traceback (most recent call last):
  File "C:\users\x\firefox-decrypt.py", line 965, in <module>
    main()
  File "C:\users\x\firefox-decrypt.py", line 946, in main
    csv_quotechar=args.quotechar,
  File "C:\users\x\firefox-decrypt.py", line 556, in decrypt_passwords
    csv_writer.writerow(output)
  File "C:\Program Files\Python37\lib\csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Program Files\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03a7' in position 30: character maps to <undefined>

The symbol \u03a7 seems to be Greek capital Chi, no idea why that is in one of my entries but whatever.

I was able to work around the bug by changing line 555 from `if PY3:` to `if PY3 and False:`, i.e. forcing it to use the encoding on line 558. The csv output now entirely consists of entries like this:

    "b'https://example.com'";"b'example'";"b'password'"

Not ideal, but I can work with it. I'm only using this to run a diff between my newer Windows install and my older Linux install, copy a few passwords to the older install, and be able to uninstall Windows altogether. (I can't just move the profile because the old one has an older Firefox due to add-on incompatibility.)

**Your system (please complete the following information):**

 - OS/System: Windows 10 - custom locale (e.g. ISO date format) - 64bits
 - Firefox 61.0.2 64 bits
 - Python: 3.7.0 64 bits
 - firefox_decrypt: pulled from Github on 2018-09-04 21:00

**Comment by unode** [comment]
Interesting! Thanks for the detailed bug report.

This falls under the category of _yet another encoding problem_ and related to #25 , but on output instead of password decoding.

This needs to wait for #29 but also needs a test to capture this use-case and the fact that it affects the encoding of `sys.stdout`.

https://bugs.python.org/issue14192 describes the reason why this happens.

This will be fixed before 1.0 is out.

**Comment by lgommans** [comment]
In case it helps, it's in the username field (so technically not 'password decoding', though it might pass through the same process). The site for which it is stored doesn't look like it would accept such input, and I also wouldn't know how to make such a symbol on my keyboard so I find it unlikely that I actually used this. I think Firefox took some wrong value when storing the password. It's not a bug in the tool, since the symbol also shows up in Firefox' password manager.

When running the tool on Linux, everything works fine out of the box.

In this case, it was only one entry, and not an important one at all. Thanks for all the work on this tool!

**Comment by unode** [comment]
Yes that's useful information. I'll incorporate all this feedback into tests to make sure they are addressed.

My main platform is Linux (as is for the largest fraction of users) so all these encoding issues affecting Windows were things that only revealed themselves recently.

**Comment by unode** [comment]
Several UTF-8 related encoding issues have been fixed in recent commits.
Running in [UTF-8 mode](https://github.com/unode/firefox_decrypt#windows) should also address the above issue.
