### ISSUE TITLE
using a profile folder with no firefox installed and no profiles.ini

### ISSUE THREAD

**Issue by beppe9000** [unode/firefox_decrypt#42]
I think there should be a way to point the script to a specific profile folder.

**Comment by unode** [comment]
There is, please check the [usage](https://github.com/unode/firefox_decrypt#usage) documentation.

`python firefox_decrypt.py /folder/containing/profiles.ini/`

**Comment by beppe9000** [comment]
I meant without having a profiles.ini file.

**Comment by unode** [comment]
Have you tried `python firefox_decrypt.py profile_folder`?

**Comment by beppe9000** [comment]
well I couldn't get past #41 so i didn't...
