### ISSUE TITLE
Make project PEP8-compliant?

### ISSUE THREAD

**Issue by 1kastner** [unode/firefox_decrypt#44]
**Is your feature request related to a problem? Please describe.**
No, I just like standardized code :)

**Describe the solution you'd like**
Adjust to coding standards, that means especially to introduce line breaks at appropriate places.
Add e.g. flake8 to `wercker.yml`, maybe as it has been done at [this example](https://github.com/AntreasAntoniou/DeepClassificationBot/blob/master/wercker.yml)

**Describe alternatives you've considered**
There might be more scripts which could do a similar job

**Additional context**
I just tried running `flake8` locally and the output was this:

<details>
    .\firefox_decrypt.py:162:80: E501 line too long (80 > 79 characters)
    .\firefox_decrypt.py:200:80: E501 line too long (88 > 79 characters)
    .\firefox_decrypt.py:265:80: E501 line too long (86 > 79 characters)
    .\firefox_decrypt.py:266:80: E501 line too long (90 > 79 characters)
    .\firefox_decrypt.py:272:80: E501 line too long (80 > 79 characters)
    .\firefox_decrypt.py:297:80: E501 line too long (81 > 79 characters)
    .\firefox_decrypt.py:302:80: E501 line too long (80 > 79 characters)
    .\firefox_decrypt.py:323:80: E501 line too long (82 > 79 characters)
    .\firefox_decrypt.py:335:80: E501 line too long (103 > 79 characters)
    .\firefox_decrypt.py:388:80: E501 line too long (84 > 79 characters)
    .\firefox_decrypt.py:408:80: E501 line too long (98 > 79 characters)
    .\firefox_decrypt.py:440:80: E501 line too long (98 > 79 characters)
    .\firefox_decrypt.py:469:80: E501 line too long (92 > 79 characters)
    .\firefox_decrypt.py:507:80: E501 line too long (101 > 79 characters)
    .\firefox_decrypt.py:538:80: E501 line too long (100 > 79 characters)
    .\firefox_decrypt.py:539:80: E501 line too long (118 > 79 characters)
    .\firefox_decrypt.py:558:80: E501 line too long (95 > 79 characters)
    .\firefox_decrypt.py:593:80: E501 line too long (84 > 79 characters)
    .\firefox_decrypt.py:606:80: E501 line too long (84 > 79 characters)
    .\firefox_decrypt.py:623:80: E501 line too long (88 > 79 characters)
    .\firefox_decrypt.py:666:80: E501 line too long (88 > 79 characters)
    .\firefox_decrypt.py:714:80: E501 line too long (84 > 79 characters)
    .\firefox_decrypt.py:791:80: E501 line too long (84 > 79 characters)
    .\firefox_decrypt.py:818:80: E501 line too long (124 > 79 characters)
    .\firefox_decrypt.py:828:80: E501 line too long (112 > 79 characters)
    .\firefox_decrypt.py:839:80: E501 line too long (80 > 79 characters)
    .\firefox_decrypt.py:846:80: E501 line too long (88 > 79 characters)
    .\firefox_decrypt.py:850:80: E501 line too long (90 > 79 characters)
    .\firefox_decrypt.py:852:80: E501 line too long (96 > 79 characters)
    .\firefox_decrypt.py:856:80: E501 line too long (102 > 79 characters)
    .\firefox_decrypt.py:858:80: E501 line too long (103 > 79 characters)
    .\firefox_decrypt.py:860:80: E501 line too long (97 > 79 characters)
    .\firefox_decrypt.py:861:80: E501 line too long (83 > 79 characters)
    .\firefox_decrypt.py:867:80: E501 line too long (87 > 79 characters)
    .\firefox_decrypt.py:872:80: E501 line too long (106 > 79 characters)
    .\firefox_decrypt.py:876:80: E501 line too long (116 > 79 characters)
    .\firefox_decrypt.py:921:80: E501 line too long (90 > 79 characters)
    .\firefox_decrypt.py:925:80: E501 line too long (108 > 79 characters)
    .\firefox_decrypt.py:957:80: E501 line too long (80 > 79 characters)
<details/>

**Comment by unode** [comment]
Hi there,

Thanks for the report. I'm a big fan of PEP8 myself but after several years following it, I find 80 characters to be too limiting and often damaging for readability.

Nowadays I generally use flake8 with:
```
[flake8]
ignore = E501
max-line-length = 120
```
You can tell from the 120 line that I tried different lengths before ignoring E501 as a whole.

I agree that some lines could be formatted to stay below 120 with no significant impact but hitting 80 characters is something I won't pursue.

**Comment by 1kastner** [comment]
Ah ok, so it is part of the process but not part of the wercker pipeline.

**Comment by unode** [comment]
I've considered this (also for TravisCI) but never got to implement it.

I'd be ok with adding it as long as `E501` is ignored. If you feel like submitting a pull request I'd gladly accept it.
