### ISSUE TITLE
Export more fields

### ISSUE THREAD

**Issue by CoSoCo** [unode/firefox_decrypt#46]
**Is your feature request related to a problem? Please describe.**
There may be problems when importing passwords from the current output. See issue #47 .

**Describe the solution you'd like**
Additionally export all fields, e.g.: transport prefix, comment, field name login, field name password.

**Describe alternatives you've considered**

**Additional context**
When using the addon "Password Exporter" on old versions of Mozilla there are 7 fields shown: url. login, password, transport prefix, comment, field name login, field name password.

**Comment by unode** [comment]
The only ones I can see being useful are:
 ```
timeCreated
timeLastUsed
timePasswordChanged
timesUsed
```
Everything else is uninformative/unreliable. There is no `comment` field.

These are stored unencrypted so they are easier to obtain but also require a slightly different API to access or some refactoring of the code.

Pull requests are welcome

**Comment by CoSoCo** [comment]
> The only ones I can see being useful are:
> ```
> timeCreated
> timeLastUsed
> timePasswordChanged
> timesUsed
> ```
These fields may additionally be of value.
> Everything else is uninformative/unreliable. There is no `comment` field.

I was in error referring to "Password Exporter". The listed fields I got from "Saved Password Editor", see (in German): ![saved password editor](https://user-images.githubusercontent.com/14809606/48872918-9ce2b200-edeb-11e8-8920-a11830c3d197.png).
But if I remember correct, those fields were exported by "Password Exporter", which I guess are important for the later import by this addon.

**Comment by unode** [comment]
It's unlikely that this will be implemented. If there's still interest feel free to reopen.
