### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Melidebby** [unode/firefox_decrypt#50]
What file does this open too view the passwords?

Is it opening and decrypting logins.json?

Does it require the key3.db file?

**Comment by unode** [comment]
See [test Firefox v.20](https://github.com/unode/firefox_decrypt/tree/master/tests/test_data/test_profile_firefox_20), [test Firefox v.46](https://github.com/unode/firefox_decrypt/tree/master/tests/test_data/test_profile_firefox_46) or [test Firefox v.59](https://github.com/unode/firefox_decrypt/tree/master/tests/test_data/test_profile_firefox_59) for a minimal set of files necessary.
