### ISSUE TITLE
I get the error, while running in Linux

### ISSUE THREAD

**Issue by mismailzz** [unode/firefox_decrypt#60]
`ismi@kali:~/Downloads/firefox_decrypt-master$ sudo python firefox_decrypt.py --list`

> 2020-04-17 23:07:16,733 - WARNING - profile.ini not found in /root/.mozilla/firefox
> 2020-04-17 23:07:16,733 - WARNING - Continuing and assuming '/root/.mozilla/firefox' is a profile location
> 2020-04-17 23:07:16,733 - ERROR - Listing single profiles not permitted.
> 

I get this error on my current version of firefox 68.7.0.

**Comment by unode** [comment]
Nowhere in the instructions there is a mention of the `sudo` command.
Please don't blindly use it to run commands or you will risk compromising your system.

In addition, when you use `sudo` the script will no longer look for Firefox profiles under your user, where they likely exist, and instead looks in the superuser folder (i.e. `/root`) where no Firefox profile should exist.
