### ISSUE TITLE
There's no way to pass Master password if "--no-interactive" enabled (Windows)

### ISSUE THREAD

**Issue by dns** [unode/firefox_decrypt#62]
There's no way to pass Master password if "**--no-interactive**" enabled (Windows).

`python firefox_decrypt.py -nc 2`
```
2020-06-08 05:51:20,312 - INFO - Running firefox_decrypt version: 0.8.0+git
Traceback (most recent call last):
  File "firefox_decrypt.py", line 1010, in <module>
    main()
  File "firefox_decrypt.py", line 985, in main
    nss.authenticate(args.interactive)
  File "firefox_decrypt.py", line 498, in authenticate
    password = ask_password(self.profile, interactive)
  File "firefox_decrypt.py", line 787, in ask_password
    if sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

There should be an option to allow Master password can be passed from command line argument, eg:

`python firefox_decrypt.py -nc 2 --password "abc123"`

---------

 - OS/System: Windows 10 64 bit
 - Firefox 77.0.1 - 64bit
 - Python: 3.8.3 - 64 bit
 - firefox_decrypt:  0.8.0+git

**Comment by unode** [comment]
Reading from STDIN as documented [in advanced usage](https://github.com/unode/firefox_decrypt#advanced-usage) is how you should provide the password.
The fact `--password` is not available is deliberate as this would cause your password to end up in the shell's history.

However [`select()` works differently on Windows](https://stackoverflow.com/a/22254123) causing the error in your report. It also seems that most alternatives are rather non-trivial.

As I'm not a Windows user and #29 is still to be finalized, I'm afraid I will have to mark this feature as unsupported on Windows for the time being.

**Comment by dns** [comment]
Windows command prompt doesn't save history when a session ends.

**Comment by unode** [comment]
The fact that it doesn't do so by default doesn't mean [it's not possible](https://www.howtogeek.com/298163/how-to-use-your-command-history-in-the-windows-command-prompt/). The same is true for [PowerShell](https://superuser.com/questions/880213/automatically-export-history-at-end-of-powershell-session).

In other systems and shells saving the history is the default behaviour.

**Comment by dns** [comment]
No, it's not possible to access  Command prompt history after session ends. 
This is from your [link](https://www.howtogeek.com/298163/how-to-use-your-command-history-in-the-windows-command-prompt/):
> Unlike Linux’s bash shell, the Command Prompt doesn’t remember commands between sessions. To erase the history of any commands you typed, just close the Command Prompt window.

**Comment by unode** [comment]
I'm sorry but this is beyond point. The fact that `cmd.exe` has limited ability to handle history will not affect the decision.

I do not plan to support `--password` but I do intend to fix the error you pasted above which is due to a limitation on Windows.

**Comment by dumplinghusky** [comment]
Hey, I was just reading through and I think I might be able to help. If you don't want the password to be stored why not have it store a windows specific key that only the program can understand? For example it would Cesar shift the password string - N times (so abc would become bcd with +1, you can apply it to different strings) and store that key as another value. I might be completely over thinking this but if you are interested I can create a branch?

**Comment by unode** [comment]
@dumplinghusky Thanks for picking up on this. I have not managed to dedicate enough time so solve this.

If I understand your suggestion correctly, you are proposing to use a shifting cipher to obfuscate the password. This is unfortunately as secure as having the password in plain text.
As for obtaining the password from other software, this is what the `select()` approach above is trying to provide. The solution works on Linux and MacOS but unfortunately not Windows.
Adding support to interface with other software is a possibility but I don't want to add support to software I can't test myself. 

Instead, the `select()` problem identified above could be solved by something along the lines of https://stackoverflow.com/a/35889952 , time permitting. A PR on this would be much appreciated.

**Comment by dumplinghusky** [comment]
I did not completely think that one through, I got too excited. I am very interested in this project. let me spend some time reading up on all this, thanks for the reply!   
  
  

  
  
>
