### ISSUE TITLE
Encryption of the firefox passwords database

### ISSUE THREAD

**Issue by DarkFighterLuke** [unode/firefox_decrypt#64]
I ended up here searching a way to import passwords from an Opera exported CSV. I was able to find a lot of projects decrypting the firefox database, but any that can encrypt again it.

This feature would be very useful because you would be able to add new contents automatically (and not one by one using firefox lockwise) and the re-encrypt database.

I think it should not be so complex, just reversing the procedure used to decrypt, but I am not very expert in cryptography.

**Comment by unode** [comment]
Hi @DarkFighterLuke, thanks for your feedback.

Please see #56 and the discussion there.

Closing as duplicate.
