### ISSUE TITLE
I have no idea what I am doing please help

### ISSUE THREAD

**Issue by teakwood48** [unode/firefox_decrypt#65]
I've never used python before but am trying to decrypt my email password from firefox (haven't had any luck updating my firefox profile)! I've located the enrypted password but don't know how to use python. If anybody can help I would be so grateful. I will literally pay you.

**Comment by teakwood48** [comment]
Alternatively, if anybody is able to decrypt the text on their own and send the password back to me I am also open to that option, this is my only way of getting back into that email account

**Comment by unode** [comment]
Hi @teakwood48 I'm afraid your use-case is beyond the scope of this tool.
You may want to look into [Firefox support](https://support.mozilla.org/en-US/products/firefox) or the [user community](https://support.mozilla.org/en-US/get-involved).
