### ISSUE TITLE
logger syntax error

### ISSUE THREAD

**Issue by procraste** [unode/firefox_decrypt#67]
I'm beginning to use PASS on my Linux PC. So i wanted to test your script 
I've download the latest ```firefox_decrypt.py``` and tried running ```python firefox_decrypt.py```.
I get this syntax error with python 2: 
```
  File "firefox_decrypt.py", line 40
    LOG: logging.Logger
       ^
SyntaxError: invalid syntax
```
With Python 3:
```
Traceback (most recent call last):
  File "firefox_decrypt.py", line 46, in <module>
    PWStore = list[dict[str, str]]
TypeError: 'type' object is not subscriptable
```

Can you help ? Thanks

**Comment by unode** [comment]
Hi @procraste . Python 2 is no longer supported. As for Python 3, I suspect your version is not recent enough.

From the first line of the [readme](https://github.com/unode/firefox_decrypt#readme) "As of 1.0.0 Python 3.9+ is required".

Does this help?

**Comment by procraste** [comment]
Hi there, 
i had 3.8 on my system ...
I installed python3.9 and it did the job.
Thank you for your help
