### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by FalconTC** [unode/firefox_decrypt#72]
Hi Unode and thank you very much for your work !

When first running the code, I stumble over the following issue. Would you have any hint on how to solve it ?

Traceback (most recent call last):
  File "C:\Users\...\firefox_decrypt.py", line 46, in <module>
    PWStore = list[dict[str, str]]
TypeError: 'type' object is not subscriptable

Thank you very much !

**Comment by unode** [comment]
Hi @FalconTC, does https://github.com/unode/firefox_decrypt/issues/67#issuecomment-858155490 help?

**Comment by FalconTC** [comment]
Totally ! Skipping the first line of READ.ME is never a good idea...

Thanks ;)
