### ISSUE TITLE
Python 3.8.2 erro windows

### ISSUE THREAD

**Issue by Gabriel-Sama34** [unode/firefox_decrypt#74]
error when running in normal mode
the cmd py firefox_decrypt.py line 46 "PWStore = list [dict [str, str]]"

Traceback (most recent call last):
  File "firefox_decrypt.py", line 46, in <module>
    PWStore = list[dict[str, str]]
TypeError: 'type' object is not subscriptable

**Comment by unode** [comment]
See also the windows specific troubleshooting instructions: https://github.com/unode/firefox_decrypt#windows

**Comment by Yannakis** [comment]
...or  just use firefox_decrypt.py version [0.7.0](https://github.com/unode/firefox_decrypt/releases/tag/0.7.0)
