### ISSUE TITLE
TypeError: 'type' object is not subscriptable ERROR with firefox_decrypt.py

### ISSUE THREAD

**Issue by Yannakis** [unode/firefox_decrypt#75]
Hi,
I just tried to use firefox_decrypt.py in my win10 environment (both anaconda3 and firefox 64-Bit) but it failed with:

" File "C:\Users\jannis\Desktop\firefox_decrypt.py", line 46, in <module>
    PWStore = list[dict[str, str]]
TypeError: 'type' object is not subscriptable"

Does anyone know how that can be?
Thanks

**Comment by dglent** [comment]
Check this issue:
https://github.com/unode/firefox_decrypt/issues/74

**Comment by unode** [comment]
@dglent is probably right, you are not using Python 3.9.
See also https://github.com/unode/firefox_decrypt#windows

**Comment by Yannakis** [comment]
Yes, that's true, I'm not using python9 because I start python from anaconda3 (jupyter notebook) and there is python8 available.
I actually don't know how to use here python9.
But @dglent (I see, he must also be a Greek, Γειά σου Δημήτρη και ευχαριστώ :-) ) directed me to firefox_decrypt.py version 0.7.0 and this was the right one for python8!

**Comment by pjb1008** [comment]
Hi,
It would be more convenient to be able to use the system's own Python. The following patch lets it work on Ubuntu 20, which has Python 3.8.10.
```
diff --git a/firefox_decrypt.py b/firefox_decrypt.py
index 55f4aac..d06ebc0 100755
--- a/firefox_decrypt.py
+++ b/firefox_decrypt.py
@@ -35,7 +35,7 @@ from itertools import chain
 from subprocess import run, PIPE, DEVNULL
 from urllib.parse import urlparse
 from configparser import ConfigParser
-from typing import Optional, Iterator, Any
+from typing import Optional, Iterator, Any, List, Dict
 
 LOG: logging.Logger
 VERBOSE = False
@@ -43,7 +43,7 @@ SYSTEM = platform.system()
 SYS64 = sys.maxsize > 2**32
 DEFAULT_ENCODING = "utf-8"
 
-PWStore = list[dict[str, str]]
+PWStore = List[Dict[str, str]]
 
 # NOTE: In 1.0.0-rc1 we tried to use locale information to encode/decode
 # content passed to NSS. This was an attempt to address the encoding issues
```

**Comment by unode** [comment]
On my system Python 3.8 produces incorrect results even with the above patch.
Please use Python 3.9 or newer.

**Comment by Yannakis** [comment]
Thanks a lot!
Since I don't use Ubuntu, I'm going to try Python 3.9 on my win10 and see, whether it helps...

**Comment by unode** [comment]
Anaconda (or miniconda) now ship with Python 3.9 by default.
This can be an option if the system's version is older.

**Comment by Yannakis** [comment]
OK, @unode!
Thanks for the information!
