### ISSUE TITLE
Why jupyter notebook uses python3.9 when in anaconde3 folder is python3.8 installed?

### ISSUE THREAD

**Issue by Yannakis** [unode/firefox_decrypt#76]
Hi,

I just realized that the scripts in jupyter notebook use python3.9.1. 
I thought they should use python3.8.8 which is installed under C:\users\<account>\anaconda3

Thanks

**Comment by Yannakis** [comment]
Oh yes, sorry! That was the wrong place :-(
How can I delete this posting now?

**Comment by unode** [comment]
No need to delete. :)
