### ISSUE TITLE
Annotation error

### ISSUE THREAD

**Issue by devl00p** [unode/firefox_decrypt#77]
Hello,

With latest version on the repository (commit in july 2021), I get the following error using  python 3.8.12

```
 Traceback (most recent call last):
  File "firefox_decrypt.py", line 46, in <module>
    PWStore = list[dict[str, str]]
TypeError: 'type' object is not subscriptable
```

**Comment by unode** [comment]
Sorry, but 1st line of the README, Python 3.9+ only.
