### ISSUE TITLE
How do I get tests to pass!  Debian Bullseye

### ISSUE THREAD

**Issue by usamaidrsk** [unode/firefox_decrypt#79]
On the program returning `2021-12-29 10:19:39,084 - ERROR - Password decryption failed. Passwords protected by a Master Password!` 

```
➜  firefox_decrypt git:(master) ✗ python3.9 firefox_decrypt.py  -vvv
2021-12-29 10:26:04,392 - INFO - Running firefox_decrypt version: 1.0.0-7-gb71a030
2021-12-29 10:26:04,393 - DEBUG - Parsed commandline arguments: Namespace(profile='~/.mozilla/firefox', format=<class '__main__.HumanOutputFormat'>, csv_delimiter=';', csv_quotechar='"', csv_header=True, pass_username_prefix='', pass_prefix='web', pass_cmd='pass', interactive=True, choice=None, list=False, encoding='utf-8', verbose=3)
2021-12-29 10:26:04,393 - DEBUG - Running with encodings: stdin: utf-8, stdout: utf-8, stderr: utf-8, locale: UTF-8
2021-12-29 10:26:04,393 - DEBUG - Loading NSS library from libnss3.so
2021-12-29 10:26:04,394 - DEBUG - Loaded NSS library from libnss3.so
```

from that above, it shows that the NSS library is present, on running the test none passed
![image](https://user-images.githubusercontent.com/53287480/147637263-6a2b1d50-7da3-485d-b728-af8e04f9eee9.png)

**Comment by unode** [comment]
Tests need a `python3` binary in the PATH pointing to python 3.9.

If you inspect the file `tests/all.log` or run tests with `cd tests && ./run_all -v` you can get a little more information.

You can also try to run a test individually with `cd tests && python3 csv.t` or `cd tests && ./csv.t`.

**Comment by unode** [comment]
The commit (a3daadc09603a6cf8c4b7e49a59776340bc885e7) that was just pushed should improve the user experience if the above situation happens.

Regarding the output from `python3 firefox_decrypt.py -vvv`, does it stop after `Loaded NSS library from (...)`?

**Comment by usamaidrsk** [comment]
thanks, let me checkout with the latest commit

**Comment by usamaidrsk** [comment]
this is the result i get on running the scritp.
![image](https://user-images.githubusercontent.com/53287480/147693789-959d5f0a-5c23-413e-ba2e-eb98ad53df05.png)

and from the tests now i am getting this kind of response

`➜  tests git:(master) ✗ ./run_all -v
# json.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/json.t", line 6, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# non_interactive_choice.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/non_interactive_choice.t", line 5, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# list_profiles.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/list_profiles.t", line 6, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# direct_profile.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/direct_profile.t", line 6, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# version.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/version.t", line 5, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# list_single_profile.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/list_single_profile.t", line 6, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# profile_ini.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/profile_ini.t", line 5, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
# csv.t
# Traceback (most recent call last):
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/csv.t", line 5, in <module>
#     from simpletap.fdecrypt import lib
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 117, in <module>
#     lib = Test()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 18, in __init__
#     self.check_interpreter()
#   File "/home/usamaik/Desktop/firefox_decrypt/tests/simpletap/fdecrypt.py", line 30, in check_interpreter
#     raise Exception(f"{self.interpreter} binary has version {major}.{minor} but at least 3.9 is required")
# Exception: python3 binary has version 3.7 but at least 3.9 is required
not ok - Exit code was 1
Passed:                             0
Failed:                             8
Unexpected successes:               0
Skipped:                            0
Expected failures:                  0
Runtime:                         1.82 seconds
`

**Comment by usamaidrsk** [comment]
> after all tests are running this is the result i get on running the script. ![image](https://user-images.githubusercontent.com/53287480/147693789-959d5f0a-5c23-413e-ba2e-eb98ad53df05.png)

any help please @unode, thanks

**Comment by unode** [comment]
@usamaidrsk apologies for the delay, I was offline during this period. I'm not quite sure what is happening.
The library is detecting the password store as not protected by a master password but the username seems to be encrypted.

Which version of Firefox are you using and do you have a master password set?

**Comment by usamaidrsk** [comment]
I have no password set, and the version is` 95.0.2`

**Comment by unode** [comment]
I'm not sure what is happening. I can't replicate it on my side.
The username seems to be stored in an encoded form but in a format other than base64.
Still trying to find information about this online but not much luck so far.

Does this still happen if you create a new Firefox profile?
Can you access the passwords normally using Firefox's password management interface?

If you could create a new profile that displays this behavior and attach it here it would be useful for me to debug further.

**Comment by usamaidrsk** [comment]
let me try a new profile

**Comment by usamaidrsk** [comment]
the profile am decrypting is in some oldFirefox data, not signed in.

**Comment by unode** [comment]
It's possible you are missing some files, particularly if the original data was encrypted.

**Comment by usamaidrsk** [comment]
possibly, thanks for the help so much, 
there isn't anyway else to try it !

**Comment by unode** [comment]
If you can't open that profile using Firefox itself it will be difficult to get different results with other tools.
There's [other](https://www.nirsoft.net/utils/passwordfox.html) [software](https://github.com/glondu/nss-passwords) but I suspect the result will be the same.

**Comment by usamaidrsk** [comment]
Thanks for yours assistance @unode
