### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by mr-xhunt** [unode/firefox_decrypt#84]
while running firefox_decrypt.py it gave this error everytime i run it.
I am using python 3.6.9

File "/root/firefox_decrypt/firefox_decrypt.py", line 19
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by unode** [comment]
First line of the README indicates Python 3.9+. Please upgrade Python and try again.
