### ISSUE TITLE
nss3 from firefox developer edition isn't found

### ISSUE THREAD

**Issue by Jan69** [unode/firefox_decrypt#88]
**Describe the bug**  
firefox_decrypt doesn't detect nss3.dll

**To Reproduce**  
1. Launch `firefox_decrypt`
2. get error, `2022-09-27 21:19:09,302 - ERROR - Couldn't find or load 'nss3.dll'. This library is essential to interact with your Mozilla profile.`
3. cd into `C:\Program Files\Firefox Developer Edition`
4. launch `firefox_decrypt`
5. everything works perfectly fine

**Expected behavior**  
it would find nss3

**Logs and Screenshots** 
when it doesn't find the library: [firefox_decrypt.log](https://github.com/unode/firefox_decrypt/files/9659254/firefox_decrypt.log) 

**Your system (please complete the following information):**  
 - OS/System: Windows 10 - 64bits
 - Firefox Developer Edition 106.0b4 (64-bit)
 - Python: Python 3.9.5 (from miniconda)
 - firefox_decrypt: 1.0.0+git

**Comment by unode** [comment]
Commit 53325de4fe7f502397799d2eb25844dd1f935e3b should now address your use-case. Can you give it a try?

It will still fail if:
* there is no `nss3.dll` file in the folder
* your Python installation is 32 bits and Firefox is 64

**Comment by unode** [comment]
Has your use-case been solved?

**Comment by unode** [comment]
Closing as solved
