### ISSUE TITLE
"Feature"-Request pyproject.tml and pypi

### ISSUE THREAD

**Issue by NeffIsBack** [unode/firefox_decrypt#91]
Hi, this looks like a really cool tool.
I would like to install this script using pipx, so it is in line with my other python tools.
Would it be possible to provide a pyproject.toml file (and maybe upload it to pypi.org)?

If you don't want to deal with building the toml file i can open a PR if that is alright. Than it could be uploaded without much effort i think.

**Comment by unode** [comment]
Hi Alex,

firefox_decrypt has no dependencies beyond Python 3.9+ and standard library.
As such it never made much sense to make it installable via pip/pipx.

Currently, installation means downloading [the script from the main branch](https://raw.githubusercontent.com/unode/firefox_decrypt/master/firefox_decrypt.py) or [from one of its tags/releases](https://github.com/unode/firefox_decrypt/tags). Everything is included.

I'm happy to accept a `pyproject.toml` but it feels a bit overkill.
For the same reason and it not being designed to be used as a library, I'm not sure about including it in pypi.

That said, I'm open to be convinced given a concrete use-case.

**Comment by NeffIsBack** [comment]
Yes I absolutely agree having a poetry/pyproject.toml doesn't really make sense for dependency management in a project with no dependencies😅 The point why it would be really nice to have one is because pipx would need one to make the tool installable.

My goal is to have every Pentest tool, that is either not available or outdated on apt (e.g. CrackMapExec, impacket) installed with pipx. That makes them available system wide on the command line and very easy to update (as soon as there is a version bump in the pyproject.toml I can run ’pipx upgrade’). 

To have the tool on PyPI is just a nice addition, but installations directly from GitHub works just as well, so that wouldn't be absolutely necessary.
